/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MichaelH
 */
package mockupdv;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.*;
import static mockupdv.matrixChooser.matrixD;
import mockupdv.xyzChooser;

public class DistanceV extends javax.swing.JFrame {
    
    
//    public Visualization vis = null;

    /**
     * Creates new form DistanceV
     */
    public DistanceV() {
        initComponents();
    }
    
//    double red = 1.0;
//    double green = 1.0;
//    double blue = 1.0;
    
    List<String> allLabelsSelected = new LinkedList<>();
    List<String> allLabelsIgnored = new LinkedList<>();
    
    DefaultListModel model = new DefaultListModel();
    
    Visualization ap;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        statisticsFrame = new javax.swing.JFrame();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pearsonField = new javax.swing.JTextField();
        errorField = new javax.swing.JTextField();
        statisticsUpdate = new javax.swing.JButton();
        colorFrame = new javax.swing.JFrame();
        redField = new javax.swing.JTextField();
        greenField = new javax.swing.JTextField();
        blueField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        setColor = new javax.swing.JButton();
        labelFrame = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        labelIgnoreList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        labelSeenList = new JList(model);
        ignoreLabel = new javax.swing.JButton();
        addLabel = new javax.swing.JButton();
        colorLabel = new javax.swing.JButton();
        visPanel = new Visualization();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        button2D = new javax.swing.JToggleButton();
        positionBox = new javax.swing.JComboBox<>();
        statistics = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        labelBox1 = new javax.swing.JComboBox<>();
        labelBox2 = new javax.swing.JComboBox<>();
        labelBox3 = new javax.swing.JComboBox<>();
        addLabels = new javax.swing.JButton();
        addXY = new javax.swing.JButton();
        addMatrix = new javax.swing.JButton();
        split = new javax.swing.JCheckBox();
        splitBox = new javax.swing.JComboBox<>();
        labels = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        SVG = new javax.swing.JMenuItem();
        jpg = new javax.swing.JMenuItem();
        Exit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        freeze = new javax.swing.JCheckBoxMenuItem();
        outline = new javax.swing.JCheckBoxMenuItem();

        jFileChooser1.setMultiSelectionEnabled(true);

        statisticsFrame.setTitle("Statistics");
        statisticsFrame.setBounds(new java.awt.Rectangle(150, 150, 530, 280));

        jLabel3.setText("Pearson:");

        jLabel4.setText("Average Error:");

        pearsonField.setEditable(false);
        pearsonField.setText("jTextField1");

        errorField.setEditable(false);
        errorField.setText("jTextField1");
        errorField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                errorFieldActionPerformed(evt);
            }
        });

        statisticsUpdate.setText("Update Statistics");
        statisticsUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statisticsUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout statisticsFrameLayout = new javax.swing.GroupLayout(statisticsFrame.getContentPane());
        statisticsFrame.getContentPane().setLayout(statisticsFrameLayout);
        statisticsFrameLayout.setHorizontalGroup(
            statisticsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statisticsFrameLayout.createSequentialGroup()
                .addGroup(statisticsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(statisticsFrameLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(statisticsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(statisticsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(errorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pearsonField, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(statisticsFrameLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(statisticsUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        statisticsFrameLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {errorField, pearsonField});

        statisticsFrameLayout.setVerticalGroup(
            statisticsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statisticsFrameLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(statisticsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pearsonField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(statisticsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(errorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(statisticsUpdate)
                .addGap(51, 51, 51))
        );

        colorFrame.setMinimumSize(new java.awt.Dimension(184, 210));

        redField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redFieldActionPerformed(evt);
            }
        });

        jLabel5.setText("R:");

        jLabel6.setText("G:");

        jLabel7.setText("B:");

        setColor.setText("Set Color");
        setColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setColorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout colorFrameLayout = new javax.swing.GroupLayout(colorFrame.getContentPane());
        colorFrame.getContentPane().setLayout(colorFrameLayout);
        colorFrameLayout.setHorizontalGroup(
            colorFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(colorFrameLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(colorFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(colorFrameLayout.createSequentialGroup()
                        .addGroup(colorFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(colorFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(greenField, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(redField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(blueField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(setColor))
                .addGap(49, 49, 49))
        );
        colorFrameLayout.setVerticalGroup(
            colorFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(colorFrameLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(colorFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(redField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(colorFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(greenField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(colorFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(blueField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(27, 27, 27)
                .addComponent(setColor)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        labelFrame.setMinimumSize(new java.awt.Dimension(595, 377));

        jScrollPane1.setViewportView(labelIgnoreList);

        jScrollPane2.setViewportView(labelSeenList);

        ignoreLabel.setText("Ignore");

        addLabel.setText("Add");

        colorLabel.setText("Color");
        colorLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorLabelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout labelFrameLayout = new javax.swing.GroupLayout(labelFrame.getContentPane());
        labelFrame.getContentPane().setLayout(labelFrameLayout);
        labelFrameLayout.setHorizontalGroup(
            labelFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, labelFrameLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(labelFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addLabel, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(ignoreLabel, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(colorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        labelFrameLayout.setVerticalGroup(
            labelFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, labelFrameLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(labelFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(labelFrameLayout.createSequentialGroup()
                        .addComponent(addLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ignoreLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(colorLabel))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Distance Visualizer");

        visPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        javax.swing.GroupLayout visPanelLayout = new javax.swing.GroupLayout(visPanel);
        visPanel.setLayout(visPanelLayout);
        visPanelLayout.setHorizontalGroup(
            visPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
        );
        visPanelLayout.setVerticalGroup(
            visPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(visPanelLayout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(408, Short.MAX_VALUE))
        );

        button2D.setText("2D");
        button2D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2DActionPerformed(evt);
            }
        });

        positionBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                positionBoxActionPerformed(evt);
            }
        });

        statistics.setText("Statistics");
        statistics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statisticsActionPerformed(evt);
            }
        });

        jLabel2.setText("Labels:");

        labelBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labelBox1ActionPerformed(evt);
            }
        });

        addLabels.setText("Add Labels");
        addLabels.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLabelsActionPerformed(evt);
            }
        });

        addXY.setText("Add X/Y");
        addXY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addXYActionPerformed(evt);
            }
        });

        addMatrix.setText("Add Distance Matrix");
        addMatrix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMatrixActionPerformed(evt);
            }
        });

        split.setText("Split");
        split.setToolTipText("Separate the visualization, can only separate if there are only two labels.");
        split.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                splitActionPerformed(evt);
            }
        });

        splitBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        splitBox.setToolTipText("Separate the visualization, can only separate if there are only two labels.");
        splitBox.setEnabled(false);

        labels.setText("Add/Ignore");
        labels.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labelsActionPerformed(evt);
            }
        });

        jLabel1.setText("Position Controller:");

        jMenu1.setText("File");

        SVG.setText("Save as SVG");
        jMenu1.add(SVG);

        jpg.setText("Save as .jpg");
        jpg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpgActionPerformed(evt);
            }
        });
        jMenu1.add(jpg);

        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jMenu1.add(Exit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        freeze.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, 0));
        freeze.setText("Freeze");
        freeze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                freezeActionPerformed(evt);
            }
        });
        jMenu2.add(freeze);

        outline.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, 0));
        outline.setText("Show Outline");
        jMenu2.add(outline);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(visPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(split)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(splitBox, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(statistics)
                            .addComponent(labels)
                            .addComponent(button2D))
                        .addGap(49, 49, 49))))
            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(labelBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(217, 217, 217))
            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(labelBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(217, 217, 217))
            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(labelBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(217, 217, 217))
            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(positionBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(217, 217, 217))
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(addLabels, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addXY, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addMatrix, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(visPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button2D)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(statistics)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labels)
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(split)
                            .addComponent(splitBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(positionBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(labelBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addLabels)
                    .addComponent(addXY)
                    .addComponent(addMatrix))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button2DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2DActionPerformed
        button2D.addItemListener(new ItemListener() {
            public void itemStateChanged(ItemEvent ev) {
                if(ev.getStateChange()==ItemEvent.SELECTED){
                    System.out.println("button is selected");
                } else if(ev.getStateChange()==ItemEvent.DESELECTED){
                    System.out.println("button is not selected");
                }
            }           
        });       
    }//GEN-LAST:event_button2DActionPerformed

    private void addXYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addXYActionPerformed
        jFileChooser1.showOpenDialog(this);
        File xyzPosition = jFileChooser1.getSelectedFile();
        positionBox.addItem(xyzPosition.getName());
        try {
            xyzChooser position = new xyzChooser(xyzPosition);
            ((Visualization)visPanel).addXyz(position);
            ((Visualization)visPanel).repaint();
            //System.out.println(DistanceChooser.xpos.get(0));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_addXYActionPerformed

    private void statisticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statisticsActionPerformed
        statisticsFrame.setVisible(true);
    }//GEN-LAST:event_statisticsActionPerformed

    private void freezeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_freezeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_freezeActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void jpgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpgActionPerformed

    private void addLabelsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLabelsActionPerformed
        jFileChooser1.showOpenDialog(this);
        File labels = jFileChooser1.getSelectedFile();
        
        String[] labelTitle = labels.getName().split("-");
        int size = labelTitle.length;
        
        labelBox1.addItem(labelTitle[size - 1]);
        labelBox2.addItem(labelTitle[size - 1]);
        labelBox3.addItem(labelTitle[size - 1]);
        
        try {
            Labeling labelPos = new Labeling(labels);
            model.addElement(labels.getName());
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
    }//GEN-LAST:event_addLabelsActionPerformed

    private void addMatrixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMatrixActionPerformed
        jFileChooser1.showOpenDialog(this);
        File matrixPos = jFileChooser1.getSelectedFile();
        try {
            matrixChooser position = new matrixChooser(matrixPos);
            //System.out.println(matrixChooser.matrixD.size());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_addMatrixActionPerformed

    private void statisticsUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statisticsUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statisticsUpdateActionPerformed

    private void labelBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labelBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_labelBox1ActionPerformed

    private void errorFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_errorFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_errorFieldActionPerformed

    private void splitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_splitActionPerformed
        if (split.isSelected()){
            splitBox.setEnabled(true);
        } 
        if (!split.isSelected()){
            splitBox.setEnabled(false);
        }
           
    }//GEN-LAST:event_splitActionPerformed

    private void labelsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labelsActionPerformed
        // TODO add your handling code here:                                      
        labelFrame.setVisible(true);  
    }//GEN-LAST:event_labelsActionPerformed

    private void colorLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorLabelActionPerformed
        // TODO add your handling code here:
        colorFrame.setVisible(true);
        
    }//GEN-LAST:event_colorLabelActionPerformed

    private void redFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_redFieldActionPerformed

    private void setColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setColorActionPerformed
        // TODO add your handling code here:
//        red = Double.parseDouble(redField.getText());
//        green = Double.parseDouble(greenField.getText());
//        blue = Double.parseDouble(blueField.getText());
    }//GEN-LAST:event_setColorActionPerformed

    private void positionBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_positionBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_positionBoxActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DistanceV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DistanceV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DistanceV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DistanceV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DistanceV().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Exit;
    private javax.swing.JMenuItem SVG;
    private javax.swing.JButton addLabel;
    private javax.swing.JButton addLabels;
    private javax.swing.JButton addMatrix;
    private javax.swing.JButton addXY;
    private javax.swing.JTextField blueField;
    private javax.swing.JToggleButton button2D;
    private javax.swing.JFrame colorFrame;
    private javax.swing.JButton colorLabel;
    private javax.swing.JTextField errorField;
    private javax.swing.JCheckBoxMenuItem freeze;
    private javax.swing.JTextField greenField;
    private javax.swing.JButton ignoreLabel;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenuItem jpg;
    private javax.swing.JComboBox<String> labelBox1;
    private javax.swing.JComboBox<String> labelBox2;
    private javax.swing.JComboBox<String> labelBox3;
    private javax.swing.JFrame labelFrame;
    private javax.swing.JList<String> labelIgnoreList;
    private javax.swing.JList<String> labelSeenList;
    private javax.swing.JButton labels;
    private javax.swing.JCheckBoxMenuItem outline;
    private javax.swing.JTextField pearsonField;
    private javax.swing.JComboBox<String> positionBox;
    private javax.swing.JTextField redField;
    private javax.swing.JButton setColor;
    private javax.swing.JCheckBox split;
    private javax.swing.JComboBox<String> splitBox;
    private javax.swing.JButton statistics;
    private javax.swing.JFrame statisticsFrame;
    private javax.swing.JButton statisticsUpdate;
    private javax.swing.JPanel visPanel;
    // End of variables declaration//GEN-END:variables
}
